name: HelloXR
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  # 1. Main Application
  HelloXR:
    type: application
    platform: iOS
    sources:
      - path: Sources/HelloXR
    dependencies:
      # Embed the App Clip into the Main App
      - target: HelloXRClip
        embed: true
    settings:
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0
      # Link the Associated Domain (replace with your Team ID)
      CODE_SIGN_ENTITLEMENTS: "HelloXR.entitlements"

  # 2. App Clip Target
  HelloXRClip:
    type: app-clip
    platform: iOS
    sources:
      # Reuse the exact same source code
      - path: Sources/HelloXR
    settings:
      # App Clips behave like the main app but need the .Clip suffix
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.Clip
      
      # App Clips need a specific Info.plist configuration
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO 
      
      # Ensure it uses the same Icon (or a specific AppClipIcon if you prefer)
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXRClip.entitlements"