name: HelloXR
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  HelloXR:
    type: application
    platform: iOS
    sources:
      - path: Sources/HelloXR
    settings:
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      RECOMMENDED_ASSET_TYPES: "appicon"
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0