targets:
  HelloXR:
    type: application
    platform: iOS
    sources:
      - path: Sources/HelloXR
    dependencies:
      - target: HelloXRClip
        embed: true
    settings:
      # Points to the Main App Plist
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXR.entitlements"

  HelloXRClip:
    type: application.on-demand-install-capable
    platform: iOS
    sources:
      - path: Sources/HelloXR
    settings:
      # Points to the App Clip Plist
      INFOPLIST_FILE: Info-Clip.plist
      GENERATE_INFOPLIST_FILE: NO
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.Clip
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXRClip.entitlements"