name: HelloXR
options:
  bundleIdPrefix: ${BUNDLE_ID}
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
targets:
  HelloXR:
    type: application
    platform: iOS
    sources:
      - path: Sources/HelloXR
    dependencies:
      # Embed the App Clip into the Main App
      - target: HelloXRClip
        embed: true
    settings:
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXR.entitlements"

  HelloXRClip:
    type: application.on-demand-install-capable 
    platform: iOS
    sources:
      - path: Sources/HelloXR
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.Clip
      
      INFOPLIST_FILE: Info.plist
      GENERATE_INFOPLIST_FILE: NO 
      
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      
      CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
      MARKETING_VERSION: 1.0.0
      SWIFT_VERSION: 5.0
      CODE_SIGN_ENTITLEMENTS: "HelloXRClip.entitlements"